### ISSUE TITLE
Update built versions in `publish`

### ISSUE THREAD

**Issue by loraine-gueguen** [UweKeim/trello2gitlabextended#1]
Thanks a lots for this great extended version of trello2gitlab !
Would it be possible to update the built version of the new code in the `publish` directory (personnaly interested in the linux-x64 executable) ?
Regards

**Comment by UweKeim** [comment]
Is it not possible for you to manually build it on your system?

**Comment by loraine-gueguen** [comment]
I have never handled C# projects, I don't know the requirements and the commands to build the executables...

**Comment by UweKeim** [comment]
OK, I'll give it a try.

**Comment by UweKeim** [comment]
This is a quick manual release of the Linux x64 version:

https://github.com/UweKeim/trello2gitlabextended/releases/download/trial/trello2gitlab-linux-x64.zip

Can you please give it a try whether this works for you?

I honestly only ran my version on Windows so issues might occur on Linux. Just give me a feedback and I'll try to fix it 😊

À bientôt 👋🏻

**Comment by loraine-gueguen** [comment]
For now, I have only tested `./trello2gitlab  ../../options.json --associatewithtrello` which gives me the following error:

```
$ ./trello2gitlab  ../../options.json --associatewithtrello
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Trello2GitLab.ConsoleApp.Program.Main(String[] args)
   at Trello2GitLab.ConsoleApp.Program.<Main>(String[] args)
Abandon (core dumped)
```
But this is working fine with action added in the `options.json` file. Thanks a lot!

BTW, a few issues failed to be added a comment with the source trello card url, and the program exited, without any clear reason. The solution was to manually add the comment to the failing issues.

```
Unhandled exception. Trello2GitLab.Conversion.ApiException: 429 Too Many Requests {"message":{"error":"This endpoint has been requested too many times. Try again later."}}
   at Trello2GitLab.Conversion.GitLab.GitLabApi.Request[T](HttpMethod method, String endpoint, Nullable`1 userId, HttpContent content, Boolean projectBasedUrl)
   at Trello2GitLab.Conversion.GitLab.GitLabApi.Request[T](HttpMethod method, String endpoint, Nullable`1 userId, Object serializableContent, Boolean projectBasedUrl)
   at Trello2GitLab.Conversion.GitLab.GitLabApi.CommentIssue(Issue issue, NewIssueNote comment, Nullable`1 commentedBy)
   at Trello2GitLab.Conversion.Converter.associateIssueWithTrelloCard(Card card, Issue issue, Nullable`1 createdBy)
   at Trello2GitLab.Conversion.Converter.AssocitateWithTrello(IProgress`1 progress)
   at Trello2GitLab.ConsoleApp.Program.RunAssocitateWithTrello(ConverterOptions options)
   at Trello2GitLab.ConsoleApp.Program.Main(String[] args)
   at Trello2GitLab.ConsoleApp.Program.<Main>(String[] args)
Abandon (core dumped)
```

**Comment by UweKeim** [comment]
Thanks for you feedback.

Can you work with the current version for now or are the reported errors show stoppers for you?

Since I never intended to make this tool totally polished, personally I can live with these errors if a workaround exists (which does if I read your comment correctly).

**Comment by UweKeim** [comment]
I've now added the latest binaries to the `/publish` folder again.

**Comment by loraine-gueguen** [comment]
> Can you work with the current version for now

yes definitely ! Thanks a lot for your reactivity and your help !

Tchüss !
